FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MiPrimeraApi.csproj", "./"]
RUN dotnet restore "MiPrimeraApi.csproj"
COPY . .
RUN dotnet publish "MiPrimeraApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "MiPrimeraApi.dll"]